_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.8.10
            "5": 0.18.6
            "6": 4.46.2
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
