pretrain:
	bash run_pretrain.sh
finetune:
	bash run_finetune.sh
evaluate:
	bash run_evaluate.sh
pretrain_mini:
	bash run_pretrain_.sh
finetune_mini:
	bash run_finetune_.sh
evaluate_mini:
	bash run_evaluate_.sh
f: finetune evaluate
all: pretrain finetune evaluate
mini: pretrain_mini finetune_mini evaluate_mini